### ISSUE TITLE
schema<T>

### ISSUE THREAD

**Issue by robbiemu** [robturtle/ts-transformer-interface#3]
I am wanting to make a function like:

```ts
export function factoryInterface<T>(template = <Partial<T>>{}): T {
  const keyCollection: (string | number | symbol)[] = schema<T>().props.map(
    prop => prop.name
  );
  const data = <Partial<T>>{};

  Object.keys(template)
    .filter(key => keyCollection.includes(<keyof T>key))
    .forEach(key => (data[<keyof T>key] = template[<keyof T>key]));

  keyCollection.forEach(key => {
    if (!data.hasOwnProperty(key)) {
      data[<keyof T>key] = undefined;
    }
  });

  return data as T;
}```

so that I can use it like:
```ts
export interface FirebaseUser {
  uid: string;
  displayName?: string;
  email?: string;
  phoneNumber?: string;
  emailVerified: boolean;
  isAnonymous?: boolean;
}
console.log('default firebaseuser object', factoryInterface<FirebaseUser>())
```

With this transformer, `schema<T>()` inst valid at all. further, `schema<Partial<T>>()`also doesn't work. It seems like I must apply usage like:

```ts
/** in fact, obviously this first function now is essentially just an objectFromKeys function, but just to do the minimum change to the function: */
export function factoryInterface<T>(keyCollection: (string | number | symbol)[] = [], template = <Partial<T>>{}): T {
  const data = <Partial<T>>{};

  Object.keys(template)
    .filter(key => keyCollection.includes(<keyof T>key))
    .forEach(key => (data[<keyof T>key] = template[<keyof T>key]));

  keyCollection.forEach(key => {
    if (!data.hasOwnProperty(key)) {
      data[<keyof T>key] = undefined;
    }
  });

  console.log(keyCollection, data)

  return data as T;
} 

//...

console.log("firebase user schema", factoryInterface<FirebaseUser>(schema<FirebaseUser>().props.map(n => n.name), {}));
```

is there any way to use this generically, so  I don0't have to write _factoryInterface_ methods for each interface, and also don't have to write such a convoluted call to get the object?

**Comment by robturtle** [comment]
Unfortunately, this is out the capability of the transformer. 

This transformer is nothing but a macro-expander. Meaning you can consider `schema<User>()` equivalent to `{ name: "User", props: [...] }`, where the type argument of `schema` must be a concrete type. Using a type parameter as the type argument for `schema` is not supported.

I'm not saying it's 100% impossible to implement but it's definitely out of the ability of the TypeScript compiler. If you wish the macro can be parameterized within another structure, this implies the structure can be of any arbitrary depth. And in order to macro-expanding such a structure, you have to trace back the source code until its top level where the concrete type was passed in.
